services:
  api:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - DB_HOST=jdbc:postgresql://postgres:5432/postgres
      - DB_USERNAME=postgres
      - DB_PASSWORD=Postgres123
      - CORS_ORIGENS=*
    networks:
      - urlshortener
    ports:
      - "8080:8080"

  postgres:
    image: 'postgres'
    environment:
      POSTGRES_PASSWORD: "Postgres123"
    ports:
      - "5432:5432"
    networks:
      - urlshortener

networks:
  urlshortener:
    driver: bridge